name: Certificate Checker

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: write # allow push to repo

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - run: python certificate_checker.py

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check for file changes
        id: changes
        run: |
          git add summary_report.txt certificati_iso_date_with_status.xlsx
          if git diff --cached --quiet; then
            echo "push_required=false" >> $GITHUB_OUTPUT
          else
            echo "push_required=true" >> $GITHUB_OUTPUT
            git commit -m "Update summary and Excel file from workflow run"
          fi

      - name: Push changes
        if: steps.changes.outputs.push_required == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force_with_lease: true

      - name: Debug summary_report.txt
        run: |
          echo "---- summary_report.txt contents ----"
          cat summary_report.txt || echo "summary_report.txt not found"
          echo "------------------------------------"

      - name: Read summary report
        id: read_summary
        run: |
          printf '%s\n' "body<<EOF" >> $GITHUB_OUTPUT
          cat summary_report.txt >> $GITHUB_OUTPUT
          printf '\n' >> $GITHUB_OUTPUT
          printf '%s\n' "You can download the summary report from here:" >> $GITHUB_OUTPUT
          printf '%s\n' "https://github.com/cyberdevnet/ssl_checker/blob/main/summary_report.txt" >> $GITHUB_OUTPUT
          printf '\n' >> $GITHUB_OUTPUT
          printf '%s\n' "The Excel file used for this report is available here:" >> $GITHUB_OUTPUT
          printf '%s\n' "https://github.com/cyberdevnet/ssl_checker/blob/main/certificati_iso_date_with_status.xlsx" >> $GITHUB_OUTPUT
          printf '\nEOF\n' >> $GITHUB_OUTPUT

      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ✅ Certificate Check Completed
          to: fabriziorollo84@gmail.com
          from: "Certificate SSL Checker <fabriziorollo84@gmail.com>"
          content_type: text/html
          body: ${{ steps.read_summary.outputs.body }}
