name: Certificate Checker

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: write # needed to allow push

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - run: python certificate_checker.py

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add and commit if needed
        id: commit
        run: |
          git add summary_report.txt certificati_iso_date_with_status.xlsx
          if git diff --cached --quiet; then
            echo "push_required=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Update summary and Excel file from workflow run"
            echo "push_required=true" >> $GITHUB_OUTPUT
          fi

      - name: Force push changes
        if: steps.commit.outputs.push_required == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: false

      - name: Debug summary_report.txt
        run: |
          echo "---- summary_report.txt contents ----"
          cat summary_report.txt || echo "summary_report.txt not found"
          echo "------------------------------------"

      - name: Read summary report
        id: read_summary
        run: |
          printf '%s\n' "body<<EOF" >> $GITHUB_OUTPUT
          cat summary_report.txt >> $GITHUB_OUTPUT
          printf '\nEOF\n' >> $GITHUB_OUTPUT

      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ✅ Certificate Check Completed
          to: fabriziorollo84@gmail.com, selenerescio@gmail.com
          from: "Certificate SSL Checker <fabriziorollo84@gmail.com>"
          content_type: text/html
          body: ${{ steps.read_summary.outputs.body }}
