name: Certificate Checker

on:
  schedule:
    - cron: "0 8 * * *" # Runs every day at 08:00 UTC
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Run certificate checker
        run: python certificate_checker.py

      - name: Read summary report
        id: read_summary
        run: echo "::set-output name=body::$(cat summary_report.txt)"

      - name: Send email (via SMTP)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ✅ Certificate Check Completed
          to: fabriziorollo84@gmail.com, selenerescio@gmail.com
          from: Certificate ssl checker
          body: ${{ steps.read_summary.outputs.body }}
