name: Certificate Checker

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # We'll use GH_PAT for pushing

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - run: python certificate_checker.py

      - name: Commit and push results
        if: github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
          message: "Update summary and Excel file from workflow run"
          force: false
          files: |
            summary_report.txt
            certificati_iso_date_with_status.xlsx

      - name: Debug summary_report.txt
        run: |
          echo "---- summary_report.txt contents ----"
          cat summary_report.txt || echo "summary_report.txt not found"
          echo "------------------------------------"

      - name: Read summary report
        id: read_summary
        run: |
          printf '%s\n' "body<<EOF" >> $GITHUB_OUTPUT
          cat summary_report.txt >> $GITHUB_OUTPUT
          printf '\n' >> $GITHUB_OUTPUT
          printf '%s\n' "You can download the summary report from here:" >> $GITHUB_OUTPUT
          printf '%s\n' "https://github.com/cyberdevnet/ssl_checker/blob/main/summary_report.txt" >> $GITHUB_OUTPUT
          printf '\n' >> $GITHUB_OUTPUT
          printf '%s\n' "The Excel file used for this report is available here:" >> $GITHUB_OUTPUT
          printf '%s\n' "https://github.com/cyberdevnet/ssl_checker/blob/main/certificati_iso_date_with_status.xlsx" >> $GITHUB_OUTPUT
          printf '\nEOF\n' >> $GITHUB_OUTPUT

      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ✅ Certificate Check Completed
          to: fabriziorollo84@gmail.com
          from: "Certificate SSL Checker <fabriziorollo84@gmail.com>"
          content_type: text/html
          body: ${{ steps.read_summary.outputs.body }}
